#!/bin/sh
export PATH=/data/users/slug/install/bin:/usr/kerberos/bin:/usr/local/bin:/bin:/usr/bin:/data/users/slug/bin
cd /data/users/slug/qwebirc.org
exec cherryd -e production -d -c server.conf -i qwebirc $*
